### ISSUE TITLE
Typo -> Betriebsmodus

### ISSUE THREAD

**Issue by booze87** [schmurgel-tg/esphome#1]
select:
  - platform: template
    name: "Betriebsmodus"
    id: "select_betriebsmodus"    
    options:             
      - "AUS"       
      **- "Sommebetrieb"**
      - "Sommer-Abluftbetrieb"
      - "Winterbetrieb"      
      - "Handbetrieb"

**Comment by schmurgel-tg** [comment]
Fixed with the recent update
